---
title: "Rsa-uid3"
author: "Ben"
date: "11/20/2017"
output: html_document
---

```{r libraries message=FALSE, warning=FALSE}
library(doParallel)
library(dplyr)
library(ggplot2)
library(lme4)
library(ngram)
library(rwebppl)
library(tidyr)
```

```{r helpers}
annotateUtterance <- function(x) {
  x <- gsub(' ', '', x)
  x <- paste0('^', x)
  x <- paste0(x, '$')
  return(x)
}
```


```{r}
worldDistrStr <- "
var worldDistr = Categorical({
  vs:[{color:'a'}, {color:'b'}, {color:'c'}, {color:'d'}, {color:'e'}], 
  ps:[0.1, 0.2, 1, 1, 1]
})
"

worldDistrUnifStr <- "
var worldDistr = Categorical({
  vs:[{color:'a'}, {color:'b'}, {color:'c'}, {color:'d'}, {color:'e'}], 
  ps:[1, 1, 1, 1, 1]
})
"
```


```{r webpplModel}
modelFile <- '/Users/benpeloquin/Desktop/Projects/rsa_uid/Models/rsa-uid-corpus-generation-20171115.wppl'
baseModel <- readChar(modelFile, file.info(modelFile)$size)
unifSemanticsModel <- paste(worldDistrUnifStr, baseModel)
semanticsModel <- paste(worldDistrStr, baseModel)
```

# Experiment
```{r experimentHelpers}
runExperimentWithModel <- function(modelStr, filterSuccesses=TRUE) {
  annotateUtterance <- function(x) {
    x <- gsub(' ', '', x)
    x <- paste0('^', x)
    x <- paste0(x, '$')
    return(x)
  }
  return(
    function(theta, n, expNum) {
      # Parameters
      # ----------
      # theta: float
      #   noise level.
      # n: int
      #   number of samples.
      # expNum: int
      #   experiment number
      #
      # Returns
      # -------
      # data.frame
      #   ngram data frame
      #
      rData <- data.frame(theta=theta, n=n)
      webpplCorpus <- webppl(modelStr, data=rData, data_var='rData')
      if (filterSuccesses) {
        stream <- webpplCorpus %>%
          mutate(annotatedUtterance=annotateUtterance(currUtterance)) %>%
          filter(isSuccess) %>%  # NOTE: filtering on sussesful utterance here -- this should be reviewed.
          select(annotatedUtterance) %>%
          unlist %>%
          paste(collapse='')
      } else {
        stream <- webpplCorpus %>%
          mutate(annotatedUtterance=annotateUtterance(currUtterance)) %>%
          select(annotatedUtterance) %>%
          unlist %>%
          paste(collapse='')
      }
      ng <- ngram(stream, n=2, sep='')  # bigram model
      dfNgramRaw <- data.frame(get.phrasetable(ng))
      dfNgramRaw$first <- sapply(dfNgramRaw$ngrams, function(x) {strsplit(x, '')}[[1]][1])
      dfNgramRaw$second <- sapply(dfNgramRaw$ngrams, function(x) {strsplit(x, '')}[[1]][3])
      dfNgramRaw$theta <- theta
      dfNgramRaw$expNum <- expNum
      return(dfNgramRaw)
    }
  )
}

baseModelExpFilter <- runExperimentWithModel(baseModel)
runUnifExpFilter <- runExperimentWithModel(unifSemanticsModel)
runSemsExpFilter <- runExperimentWithModel(semanticsModel)
baseModelExpNoFilter <- runExperimentWithModel(baseModel, FALSE)
runUnifExpNoFilter <- runExperimentWithModel(unifSemanticsModel, FALSE)
runSemsExpNoFilter <- runExperimentWithModel(semanticsModel, FALSE)

runExperiments <- function(expRunFn, thetas, ns, expNums) {
  data <- mapply(expRunFn, thetas, ns, expNums, SIMPLIFY=FALSE)
  df <- do.call(rbind, data)
  rownames(df) <- 1:nrow(df)
  return(df)
}
```


```{r singleSimulationSetUp}
# iter=20, n=500, start=8:03, end=8:07
nSamples <- 100
nExps <- 30
#thetas <- c(seq(0.1, 0.9, 0.1))
thetas <- rep(0.8, nExps)
expNums <- seq(nExps)
ns <- rep(nSamples, nExps)
```

## Run first experiment
```{r runSingleSimulation}
ptm1 <- proc.time()
# Unif need probabilities
dfUnifFilter <- runExperiments(runUnifExpFilter, thetas, ns, expNums) %>%
  mutate(expType='unifSemsFilter')
ptm2 <- proc.time()
etm1 <- ptm2 - ptm1
cat('runtime: ', etm1[3] / 60)

# Differentiated need probs
dfSemsFilter <- runExperiments(runSemsExpFilter, thetas, ns, expNums) %>%
  mutate(expType='semsFilter')
ptm3 <- proc.time()
etm2 <- ptm3 - ptm2
cat('runtime: ', etm2[3] / 60)

# Unif need probabilities
dfUnifNoFilter <- runExperiments(runUnifExpNoFilter, thetas, ns, expNums) %>%
  mutate(expType='unifSemsNoFilter')
ptm4 <- proc.time()
etm3 <- ptm4 - ptm3
cat('runtime: ', etm3[3] / 60)

# Differentiated need probs
dfSemsNoFilter <- runExperiments(runSemsExpNoFilter, thetas, ns, expNums) %>%
  mutate(expType='semsNoFilter')
ptm5 <- proc.time()
etm4 <- ptm5 - ptm4
cat('runtime: ', etm4[3] / 60)
```

```{r}
dfComb <- rbind(dfUnifFilter, dfSemsFilter, dfUnifNoFilter, dfSemsNoFilter)
```


## Plot 1
```{r playground}
dfComb %>%
  # filter(expType=='sems', expNum==1) %>%
  group_by(expType, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(expType, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  ungroup %>%
  # Gut check below
  group_by(second) %>%
  summarise(total=sum(likelihood))
```


```{r plotErrorBars1}
dfComb %>%
  group_by(expType, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(expType, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  ungroup %>%
  filter(second %in% c('a', 'b', 'c', 'd', 'e'), marked) %>%
  select(expType, second, postProb, likelihood, marked) %>%
  group_by(expType, second, marked) %>%
  summarise(
    avgPostProb=mean(postProb),
    xmin=quantile(postProb, probs=c(0.025)),
    xmax=quantile(postProb, probs=c(0.975)),
    avgLikelihood=mean(likelihood),
    ymin=quantile(likelihood, probs=c(0.025)),
    ymax=quantile(likelihood, probs=c(0.975))) %>%
  ggplot(aes(x=avgPostProb, y=avgLikelihood, col=as.factor(second))) +
    geom_point() +
    geom_errorbar(aes(ymax=ymax, ymin=ymin)) +
    geom_errorbarh(aes(xmax=xmax, xmin=xmin)) +
    facet_wrap(~expType, ncol=2)
```

## Plot 2
```{r plotScatter1}
dfComb %>%
  group_by(expType, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(expType, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  filter(second %in% letters[1:5], marked) %>%
  select(expType, theta, second, marked, postProb, likelihood, expNum) %>%
  ggplot(aes(x=postProb, y=likelihood)) +
    geom_point(aes(col=second), alpha=0.7) +
    geom_rug(aes(col=second)) +
    facet_wrap(~expType)
```

## Plot 3
```{r plotFacets1}
dfComb %>%
  group_by(expType, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(expType, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  filter(second %in% letters[1:5], marked) %>%
  select(expType, theta, second, marked, postProb, likelihood, expNum) %>%
  ggplot(aes(x=postProb, y=likelihood)) +
    geom_point(aes(col=second), alpha=0.7) +
    facet_grid(expType~expNum) +
    geom_smooth(method='lm')
```

# Varying theta
```{r runSimulationsFn}
simulateAtTheta <- function(theta) {
  n <- 100
  iters <- 30
  thetas <- rep(theta, iters)
  expNums <- seq(length(thetas))
  ns <- rep(n, length(thetas))
  df <- runExperiments(runSemsExpFilter, thetas, ns, expNums)
  df
}

#df <- runExperiments(thetas, ns, expNums)
```

```{r parSimulationsSetUp}
no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type='FORK')
registerDoParallel(cl) 
```

```{r parSimulationsRun}
ptm <- proc.time()
dSims <- foreach(i=seq(0.2, 0.8, 0.2), .packages=c('dplyr', 'rwebppl'), .combine=rbind) %dopar% simulateAtTheta(i)
stopCluster(cl)
etm <- proc.time() - ptm
cat("runtime: ", etm[3] / 60)

```

```{r processSimulations}
# dfSims <- do.call(rbind, sims)
```

```{r}
dSims %>%
  group_by(theta, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(theta, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  ungroup %>%
  filter(second %in% letters[1:5], marked) %>%
  select(second, postProb, likelihood, theta) %>%
  group_by(theta, second) %>%
  summarise(
    avgPostProb=mean(postProb),
    xmin=quantile(postProb, probs=c(0.025)),
    xmax=quantile(postProb, probs=c(0.975)),
    avgLikelihood=mean(likelihood),
    ymin=quantile(likelihood, probs=c(0.025)),
    ymax=quantile(likelihood, probs=c(0.975)))
```


```{r plotErrorBars2}
dSims %>%
  group_by(theta, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(theta, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  ungroup %>%
  filter(second %in% letters[1:5], marked) %>%
  select(second, postProb, likelihood, theta) %>%
  group_by(theta, second) %>%
  summarise(
    avgPostProb=mean(postProb),
    xmin=quantile(postProb, probs=c(0.025)),
    xmax=quantile(postProb, probs=c(0.975)),
    avgLikelihood=mean(likelihood),
    ymin=quantile(likelihood, probs=c(0.025)),
    ymax=quantile(likelihood, probs=c(0.975))) %>%
  ggplot(aes(x=avgPostProb, y=avgLikelihood)) +
    geom_point(aes(col=as.factor(second)), alpha=0.5, size=1.25) +
    geom_errorbar(aes(ymax=ymax, ymin=ymin, col=as.factor(second))) +
    geom_errorbarh(aes(xmax=xmax, xmin=xmin, col=as.factor(second))) +
    geom_smooth(method='lm', se=FALSE, group=0) +
    facet_wrap(~theta)
```

```{r plotScatter2}
dSims %>%
  group_by(theta, expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(theta, expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  filter(second %in% letters[1:5], marked) %>%
  select(theta, second, marked, postProb, likelihood, expNum) %>%
  ggplot(aes(x=postProb, y=likelihood)) +
    geom_point(aes(col=second), alpha=0.5) +
    geom_rug(aes(col=second)) +
    facet_wrap(~theta)
```


# Analysis
```{r plotFacets2}
dfAgg <- df %>%
  group_by(expNum, first) %>%
  mutate(first_n=sum(freq),
         postProb=log2(freq/first_n)) %>%
  ungroup %>%
  group_by(expNum, second) %>%
  mutate(second_n=sum(freq),
         likelihood=freq/second_n,
         marked=first=='X') %>%
  filter(second %in% letters[1:5], marked) %>%
  select(theta, second, marked, postProb, likelihood, expNum)
```

```{r}
summary(lmer(likelihood~postProb + (expNum|second), data=dfAgg))
```

