---
title: "rsa-uid-corpus-generation-20171201"
author: "Ben"
date: "12/1/2017"
output: html_document
---

```{r packages, message=FALSE, warning=FALSE}
library(doParallel)
library(dplyr)
library(ggplot2)
library(tidyr)
```


```{r webpplFile}
getModelFile <- function(fPath) {
  readChar(fPath, file.info(fPath)$size)
}
fPath <- '/Users/benpeloquin/Desktop/Projects/rsa_uid/Models/rsa-uid-corpus-generation-20171201.wppl'
fPath <- '/Users/benpeloquin/Desktop/Projects/rsa_uid/Models/rsa-uid-corpus-generation-20171206.wppl'
modelStr <- getModelFile(fPath)
```

```{r utils}
newRData <- function(modelName, alpha, lambda, theta, n) {
  data.frame(modelName=modelName,
             alpha=alpha,
             lambda=lambda,
             theta=theta,
             n=n,
             stringsAsFactors=FALSE)
}
# rData <- newRData('S1', 1, 1, 0.5, 10)

createRunFn <- function(modelStr) {
  return(function(data, dataName='rData') { 
    rwebppl::webppl(modelStr, data=data, data_var=dataName)
  })
}
runFn <- createRunFn(modelStr)

runExperimentFn <- function(runFn, modelName, alpha, lambda, theta, n) {
  return(function(expNum) {
    rData <- newRData(modelName, alpha, lambda, theta, n)
    df <- runFn(rData) %>%
      mutate(modelName=modelName,
             alpha=alpha,
             lambda=lambda,
             theta=theta,
             n=n,
             expNum=expNum)
    df 
  })
}
nSamples <- 250
runExp1 <- runExperimentFn(runFn, 'S2', 1, 1, 0.5, nSamples)
runExp2 <- runExperimentFn(runFn, 'S1', 5, 1, 0.2, nSamples)
```

```{r lmAnalysisFn}
createLM <- function(dfCorpus) {
  stream <- dfCorpus %>%
          # mutate(annotatedUtterance=annotateUtterance(currUtterance)) %>%
          select(currUtterance) %>%
          unlist %>%
          paste0(collapse='') %>%
          gsub(' ', '', ., fixed=TRUE)
  ng <- ngram::ngram(stream, n=2, sep='')  # bigram model
  dfNgramRaw <- data.frame(ngram::get.phrasetable(ng))
  dfNgramRaw$first <- sapply(dfNgramRaw$ngrams, function(x) {strsplit(x, '')}[[1]][1])
  dfNgramRaw$second <- sapply(dfNgramRaw$ngrams, function(x) {strsplit(x, '')}[[1]][3])
  dfNgramRaw <- dfNgramRaw %>%
    mutate(first=ifelse(first==' ', '*', first),
           second=ifelse(second==' ', '*', second))
  dfNgramRaw$theta <- unique(dfCorpus$theta)
  dfNgramRaw$alpha <- unique(dfCorpus$alpha)
  dfNgramRaw$lambda <- unique(dfCorpus$lambda)
  dfNgramRaw$expNum <- unique(dfCorpus$expNum)
  dfNgramRaw
}
```

## Test on single run
```{r}
# S2DVVV 100 samples ~ 23s
ptm <- proc.time()
dfExp1 <- runExp1(1)
dfExp1LM <- createLM  (dfExp1)
etm <- proc.time() - ptm
cat('run time at', nSamples, ' is ', etm[3]/60)
```

```{r play1}
# 7087 total bigram counts
# 323 a's 
dfExp1 %>%
  group_by(currUtterance, currWorld, isSuccess) %>%
  summarise(n=n()) %>%
  arrange(desc(n))
```

```{r play1}
# 7087 total bigram counts
# 323 a's 
dfExp1LM %>%
  group_by(expNum, second) %>%
  mutate(secondUncondProb=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondUncondProb) %>%
  ungroup %>%
  ggplot(aes(x=first, y=lik, fill=second)) +
    geom_bar(stat='identity', position='dodge')
```


```{r}
dfExp1LM %>%
  group_by(expNum, second) %>%
  mutate(secondUncondProb=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondUncondProb) %>%    # p(X|a) = p(X a) / p(a|X) + p(a|^)
  ungroup %>%
  group_by(expNum) %>%
  mutate(logUncondProb=log2(secondUncondProb)) %>%  # p(a)
  # ungroup %>%
  # filter(first=='X') %>%
  # select(ngrams, prop, lik, postProb)
  # 
  # 
  # select(lik)
  ungroup %>%
  select(expNum, first, second, lik, logUncondProb) %>%
  filter(second %in% c(letters[1:5], '*'), first=='X') %>%
  group_by(second) %>%
  summarise(
    avgPostProb=mean(logUncondProb),
    xmin=quantile(logUncondProb, probs=c(0.025)),
    xmax=quantile(logUncondProb, probs=c(0.975)),
    avgLikelihood=mean(lik),
    ymin=quantile(lik, probs=c(0.025)),
    ymax=quantile(lik, probs=c(0.975))) %>%
  ggplot(aes(x=avgPostProb, y=avgLikelihood, col=as.factor(second))) +
    geom_point() +
    geom_errorbar(aes(ymax=ymax, ymin=ymin)) +
    geom_errorbarh(aes(xmax=xmax, xmin=xmin)) +
    ylab('Likelihood of marked version') +
    xlab('mean(log(p(utt))') +
    theme_bw()
```


## Simulations
```{r}
no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type='FORK')
registerDoParallel(cl)
```

```{r}
ptm <- proc.time()
nIters <-50
simsExp1 <- foreach(i=seq(1, nIters), .packages=c('dplyr', 'rwebppl'), .combine=rbind) %dopar% runExp1(i)
stopCluster(cl)
etm <- proc.time() - ptm
cat("runtime: ", etm[3] / 60)
```

```{r}
lSimsExp1 <- simsExp1 %>%
  group_by(expNum) %>%
  do(vals=data.frame(.)) %>%
  lapply(function(x) {(x)})

lD <- lapply(lSimsExp1$vals, function(x) {createLM(x)})
df <- do.call(rbind, lD)
```


```{r}
df %>%
  group_by(expNum, second) %>%
  mutate(secondTotalProp=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondTotalProp) %>%    # p(X|a) = p(X a) / p(a|X) + p(a|^)
  ungroup %>%
  group_by(expNum) %>%
  mutate(postProb=log2(secondTotalProp/sum(prop))) %>%  # p(a)
  ungroup %>%
  select(expNum, first, second, lik, postProb) %>%
  filter(second %in% c(letters[1:5], '*'), first=='X') %>%
  group_by(second) %>%
  summarise(
    avgPostProb=mean(postProb),
    xmin=quantile(postProb, probs=c(0.05)),
    xmax=quantile(postProb, probs=c(0.95)),
    avgLikelihood=mean(lik),
    ymin=quantile(lik, probs=c(0.05)),
    ymax=quantile(lik, probs=c(0.95)))
```


```{r}
df %>%
  group_by(expNum, second) %>%
  mutate(secondTotalProp=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondTotalProp) %>%    # p(X|a) = p(X a) / p(a|X) + p(a|^)
  ungroup %>%
  group_by(expNum) %>%
  mutate(postProb=log2(secondTotalProp/sum(prop))) %>%  # p(a)
  ungroup %>%
  select(expNum, first, second, lik, postProb) %>%
  filter(second %in% c(letters[1:5], '*'), first=='X') %>%
  group_by(second) %>%
  summarise(
    avgPostProb=mean(postProb),
    xmin=quantile(postProb, probs=c(0.05)),
    xmax=quantile(postProb, probs=c(0.95)),
    avgLikelihood=mean(lik),
    ymin=quantile(lik, probs=c(0.05)),
    ymax=quantile(lik, probs=c(0.95))) %>%
    ggplot(aes(x=avgPostProb, y=avgLikelihood, col=as.factor(second))) +
      geom_point() +
      geom_errorbar(aes(ymax=ymax, ymin=ymin, width=0)) +
      geom_errorbarh(aes(xmax=xmax, xmin=xmin, height=0)) +
      geom_smooth(group=0) +
      ylab('Likelihood of marked version') +
      xlab('mean(log(p(utt))') +
      theme_bw()
```

```{r}
df %>%
  group_by(expNum, second) %>%
  mutate(secondTotalProp=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondTotalProp) %>%    # p(X|a) = p(X a) / p(a|X) + p(a|^)
  ungroup %>%
  group_by(expNum) %>%
  mutate(postProb=log2(secondTotalProp/sum(prop))) %>%  # p(a)
  ungroup %>%
  select(expNum, first, second, lik, postProb) %>%
  filter(second %in% c(letters[1:5], '*'), first=='X') %>%
  ggplot(aes(x=postProb, y=lik, col=as.factor(second))) +
    geom_point() +
    ylab('Likelihood of marked version') +
    xlab('mean(log(p(utt))') +
    theme_bw()
```


```{r}
df %>%
  group_by(expNum, second) %>%
  mutate(secondTotalProp=sum(prop),       # p(a|X) + p(a|^)
         lik=prop/secondTotalProp) %>%    # p(X|a) = p(X a) / p(a|X) + p(a|^)
  ungroup %>%
  group_by(expNum) %>%
  mutate(postProb=log2(secondTotalProp/sum(prop))) %>%  # p(a)
  ungroup %>%
  select(expNum, first, second, lik, postProb) %>%
  filter(second %in% c(letters[1:5], '*'), first=='X') %>%
  group_by(expNum) %>%
  mutate(dist=lik - mean(lik)) %>%
  ungroup %>%
  group_by(second) %>%
  summarise(
    avgDist=mean(dist),                        # add likelihood rank
    distMin=quantile(dist, probs=c(0.05)),        # add likelihood rank
    distMax=quantile(dist, probs=c(0.95)),        # add likelihood rank
    avgPostProb=mean(postProb),
    postProbMin=quantile(postProb, probs=c(0.05)),
    postProbMax=quantile(postProb, probs=c(0.95)),
    avgLikelihood=mean(lik),
    likMin=quantile(lik, probs=c(0.05)),
    likMax=quantile(lik, probs=c(0.95))) %>%
  select(second, avgDist, distMin, distMax, avgPostProb, postProbMin, postProbMax) %>%
  ggplot(aes(x=avgPostProb, y=avgDist, col=as.factor(second))) +
      geom_point() +
      geom_errorbar(aes(ymax=distMax, ymin=distMin, width=0)) +
      geom_errorbarh(aes(xmax=postProbMax, xmin=postProbMin, height=0)) +
      ylab('Likelihood of marked version') +
      xlab('mean(log(p(utt))') +
      # ylim(-.5, .5) +
      theme_bw()
  
```



```{r}
worldPrior <- c(0.12, 0.16, 0.24, 0.48)
pXa <- c(0.68, 0.00004, 0.001, 0.04)
pa <- c(0.32, 0.00007, 0.002, 0.086)
df1 <- data.frame(world=letters[1:4], pCond=pXa, pWorld=worldPrior, form='full')
df2 <- data.frame(world=letters[1:4], pCond=pa, pWorld=worldPrior, form='partial')
dfComb <- rbind(df1, df2)
dfComb %>%
  mutate(pJoint=pCond*pWorld) %>%
  group_by(world, form) %>%
  summarize(prob=sum(pJoint)) %>%
  spread(form, prob) %>%
  mutate(ratio=full/(full+partial))
```

